export interface UserFilters {
  role?: string;
}

export interface MockUser {
  id: number;
  name: string;
  email: string;
  role: 'Admin' | 'User' | 'Manager';
  avatar: string;
}

export const MOCK_USERS: MockUser[] = [
  {
    id: 1,
    name: 'Ahmed Hassan',
    email: 'ahmed1@example.com',
    role: 'Admin',
    avatar: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: 2,
    name: 'Sara Mohamed',
    email: 'sara2@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: 3,
    name: 'Omar Ali',
    email: 'omar3@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=3',
  },
  {
    id: 4,
    name: 'Mariam Samir',
    email: 'mariam4@example.com',
    role: 'Manager',
    avatar: 'https://i.pravatar.cc/150?img=4',
  },
  {
    id: 5,
    name: 'Youssef Ahmed',
    email: 'youssef5@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=5',
  },
  {
    id: 6,
    name: 'Nour Khaled',
    email: 'nour6@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=6',
  },
  {
    id: 7,
    name: 'Karim Mostafa',
    email: 'karim7@example.com',
    role: 'Admin',
    avatar: 'https://i.pravatar.cc/150?img=7',
  },
  {
    id: 8,
    name: 'Salma Adel',
    email: 'salma8@example.com',
    role: 'Manager',
    avatar: 'https://i.pravatar.cc/150?img=8',
  },
  {
    id: 9,
    name: 'Hana Ibrahim',
    email: 'hana9@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=9',
  },
  {
    id: 10,
    name: 'Mahmoud Tarek',
    email: 'mahmoud10@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: 11,
    name: 'Laila Ashraf',
    email: 'laila11@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=11',
  },
  {
    id: 12,
    name: 'Adam Sameh',
    email: 'adam12@example.com',
    role: 'Manager',
    avatar: 'https://i.pravatar.cc/150?img=12',
  },
  {
    id: 13,
    name: 'Mina George',
    email: 'mina13@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=13',
  },
  {
    id: 14,
    name: 'Dina Wael',
    email: 'dina14@example.com',
    role: 'Admin',
    avatar: 'https://i.pravatar.cc/150?img=14',
  },
  {
    id: 15,
    name: 'Tamer Hany',
    email: 'tamer15@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=15',
  },
  {
    id: 16,
    name: 'Rana Emad',
    email: 'rana16@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=16',
  },
  {
    id: 17,
    name: 'Mostafa Adel',
    email: 'mostafa17@example.com',
    role: 'Manager',
    avatar: 'https://i.pravatar.cc/150?img=17',
  },
  {
    id: 18,
    name: 'Jana Karim',
    email: 'jana18@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=18',
  },
  {
    id: 19,
    name: 'Ola Sameh',
    email: 'ola19@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=19',
  },
  {
    id: 20,
    name: 'Hossam Nabil',
    email: 'hossam20@example.com',
    role: 'Admin',
    avatar: 'https://i.pravatar.cc/150?img=20',
  },
  {
    id: 21,
    name: 'Ahmed Hassan',
    email: 'ahmed21@example.com',
    role: 'Admin',
    avatar: 'https://i.pravatar.cc/150?img=21',
  },
  {
    id: 22,
    name: 'Sara Mohamed',
    email: 'sara22@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=22',
  },
  {
    id: 23,
    name: 'Omar Ali',
    email: 'omar23@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=23',
  },
  {
    id: 24,
    name: 'Mariam Samir',
    email: 'mariam24@example.com',
    role: 'Manager',
    avatar: 'https://i.pravatar.cc/150?img=24',
  },
  {
    id: 25,
    name: 'Youssef Ahmed',
    email: 'youssef25@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=25',
  },
  {
    id: 26,
    name: 'Nour Khaled',
    email: 'nour26@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=26',
  },
  {
    id: 27,
    name: 'Karim Mostafa',
    email: 'karim27@example.com',
    role: 'Admin',
    avatar: 'https://i.pravatar.cc/150?img=27',
  },
  {
    id: 28,
    name: 'Salma Adel',
    email: 'salma28@example.com',
    role: 'Manager',
    avatar: 'https://i.pravatar.cc/150?img=28',
  },
  {
    id: 29,
    name: 'Hana Ibrahim',
    email: 'hana29@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=29',
  },
  {
    id: 30,
    name: 'Mahmoud Tarek',
    email: 'mahmoud30@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=30',
  },
  {
    id: 31,
    name: 'Laila Ashraf',
    email: 'laila31@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=31',
  },
  {
    id: 32,
    name: 'Adam Sameh',
    email: 'adam32@example.com',
    role: 'Manager',
    avatar: 'https://i.pravatar.cc/150?img=32',
  },
  {
    id: 33,
    name: 'Mina George',
    email: 'mina33@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=33',
  },
  {
    id: 34,
    name: 'Dina Wael',
    email: 'dina34@example.com',
    role: 'Admin',
    avatar: 'https://i.pravatar.cc/150?img=34',
  },
  {
    id: 35,
    name: 'Tamer Hany',
    email: 'tamer35@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=35',
  },
  {
    id: 36,
    name: 'Rana Emad',
    email: 'rana36@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=36',
  },
  {
    id: 37,
    name: 'Mostafa Adel',
    email: 'mostafa37@example.com',
    role: 'Manager',
    avatar: 'https://i.pravatar.cc/150?img=37',
  },
  {
    id: 38,
    name: 'Jana Karim',
    email: 'jana38@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=38',
  },
  {
    id: 39,
    name: 'Ola Sameh',
    email: 'ola39@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=39',
  },
  {
    id: 40,
    name: 'Hossam Nabil',
    email: 'hossam40@example.com',
    role: 'Admin',
    avatar: 'https://i.pravatar.cc/150?img=40',
  },
  {
    id: 41,
    name: 'Ahmed Hassan',
    email: 'ahmed41@example.com',
    role: 'Admin',
    avatar: 'https://i.pravatar.cc/150?img=41',
  },
  {
    id: 42,
    name: 'Sara Mohamed',
    email: 'sara42@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=42',
  },
  {
    id: 43,
    name: 'Omar Ali',
    email: 'omar43@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=43',
  },
  {
    id: 44,
    name: 'Mariam Samir',
    email: 'mariam44@example.com',
    role: 'Manager',
    avatar: 'https://i.pravatar.cc/150?img=44',
  },
  {
    id: 45,
    name: 'Youssef Ahmed',
    email: 'youssef45@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=45',
  },
  {
    id: 46,
    name: 'Nour Khaled',
    email: 'nour46@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=46',
  },
  {
    id: 47,
    name: 'Karim Mostafa',
    email: 'karim47@example.com',
    role: 'Admin',
    avatar: 'https://i.pravatar.cc/150?img=47',
  },
  {
    id: 48,
    name: 'Salma Adel',
    email: 'salma48@example.com',
    role: 'Manager',
    avatar: 'https://i.pravatar.cc/150?img=48',
  },
  {
    id: 49,
    name: 'Hana Ibrahim',
    email: 'hana49@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=49',
  },
  {
    id: 50,
    name: 'Mahmoud Tarek',
    email: 'mahmoud50@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=50',
  },
  {
    id: 51,
    name: 'Laila Ashraf',
    email: 'laila51@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=51',
  },
  {
    id: 52,
    name: 'Adam Sameh',
    email: 'adam52@example.com',
    role: 'Manager',
    avatar: 'https://i.pravatar.cc/150?img=52',
  },
  {
    id: 53,
    name: 'Mina George',
    email: 'mina53@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=53',
  },
  {
    id: 54,
    name: 'Dina Wael',
    email: 'dina54@example.com',
    role: 'Admin',
    avatar: 'https://i.pravatar.cc/150?img=54',
  },
  {
    id: 55,
    name: 'Tamer Hany',
    email: 'tamer55@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=55',
  },
  {
    id: 56,
    name: 'Rana Emad',
    email: 'rana56@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=56',
  },
  {
    id: 57,
    name: 'Mostafa Adel',
    email: 'mostafa57@example.com',
    role: 'Manager',
    avatar: 'https://i.pravatar.cc/150?img=57',
  },
  {
    id: 58,
    name: 'Jana Karim',
    email: 'jana58@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=58',
  },
  {
    id: 59,
    name: 'Ola Sameh',
    email: 'ola59@example.com',
    role: 'User',
    avatar: 'https://i.pravatar.cc/150?img=59',
  },
  {
    id: 60,
    name: 'Hossam Nabil',
    email: 'hossam60@example.com',
    role: 'Admin',
    avatar: 'https://i.pravatar.cc/150?img=60',
  },
];
