export const formsPaths = {
  root: 'forms',
  overview: 'forms-overview',
  textInput: 'text-input',
  textArea: 'text-area',
  password: 'password-input',
  numbers: 'numbers-input',
  switch: 'switch',
  checkbox: 'checkbox',
  checkboxGroup: 'checkbox-group',
  otp: 'otp',
  datePicker: 'date-picker',
  select: 'select',
  phone: 'phone',
  radio: 'radio',
  radioGroup: 'radio-group',
  ImageUpload: 'image-upload',
  tags: 'tags-input',
  multiStepForm: 'multi-step-form',
};
